// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  roomId: __t.u64().name("room_id"),
  roundId: __t.u64().name("round_id"),
  cue: __t.u8(),
  mode: __t.string(),
  text: __t.string(),
  voiced: __t.bool(),
  at: __t.timestamp(),
});
