// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roundId: __t.u64().name("round_id"),
  kind: __t.string(),
  index: __t.u8(),
  placedBy: __t.identity().name("placed_by"),
  pending: __t.bool(),
  completesAt: __t.option(__t.timestamp()).name("completes_at"),
});
