// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Phase,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  host: __t.identity(),
  get phase() {
    return Phase;
  },
  currentRoundId: __t.option(__t.u64()).name("current_round_id"),
  nextRoundId: __t.option(__t.u64()).name("next_round_id"),
  createdAt: __t.timestamp().name("created_at"),
});
