// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoundStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  get status() {
    return RoundStatus;
  },
  planetName: __t.string().name("planet_name"),
  twist: __t.string(),
  massBudget: __t.u32().name("mass_budget"),
  cheapestMass: __t.u32().name("cheapest_mass"),
  solarPerArray: __t.f64().name("solar_per_array"),
  nightBand: __t.u8().name("night_band"),
  thermalLoad: __t.u8().name("thermal_load"),
  co2Atmosphere: __t.bool().name("co_2_atmosphere"),
  iceAvailable: __t.bool().name("ice_available"),
  bermsRequired: __t.u8().name("berms_required"),
  gravity: __t.f64(),
  headline: __t.string(),
  scaleText: __t.string().name("scale_text"),
  funFacts: __t.array(__t.string()).name("fun_facts"),
  buildEndsAt: __t.option(__t.timestamp()).name("build_ends_at"),
});
