// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BecauseInput = __t.object("BecauseInput", {
  kind: __t.string(),
  text: __t.string(),
  field: __t.string(),
});
export type BecauseInput = __Infer<typeof BecauseInput>;

export const BermDone = __t.object("BermDone", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  pieceId: __t.u64(),
});
export type BermDone = __Infer<typeof BermDone>;

export const BuildEnd = __t.object("BuildEnd", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roundId: __t.u64(),
});
export type BuildEnd = __Infer<typeof BuildEnd>;

export const BuildStart = __t.object("BuildStart", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roundId: __t.u64(),
});
export type BuildStart = __Infer<typeof BuildStart>;

export const Cursor = __t.object("Cursor", {
  identity: __t.identity(),
  roomId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  visible: __t.bool(),
});
export type Cursor = __Infer<typeof Cursor>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  roomId: __t.u64(),
  name: __t.string(),
  joinedAt: __t.timestamp(),
  online: __t.bool(),
});
export type Member = __Infer<typeof Member>;

export const ParamInput = __t.object("ParamInput", {
  field: __t.string(),
  num: __t.option(__t.f64()),
  flag: __t.option(__t.bool()),
  unit: __t.string(),
  status: __t.string(),
  sourceLabel: __t.string(),
  sourceUrl: __t.string(),
  note: __t.string(),
});
export type ParamInput = __Infer<typeof ParamInput>;

// The tagged union or sum type for the algebraic type `Phase`.
export const Phase = __t.enum("Phase", {
  Lobby: __t.unit(),
  Briefing: __t.unit(),
  Build: __t.unit(),
  Debrief: __t.unit(),
});
export type Phase = __Infer<typeof Phase>;

export const Piece = __t.object("Piece", {
  id: __t.u64(),
  roundId: __t.u64(),
  kind: __t.string(),
  index: __t.u8(),
  placedBy: __t.identity(),
  pending: __t.bool(),
  completesAt: __t.option(__t.timestamp()),
});
export type Piece = __Infer<typeof Piece>;

export const PlanetParameter = __t.object("PlanetParameter", {
  id: __t.u64(),
  roundId: __t.u64(),
  field: __t.string(),
  num: __t.option(__t.f64()),
  flag: __t.option(__t.bool()),
  unit: __t.string(),
  status: __t.string(),
  sourceLabel: __t.string(),
  sourceUrl: __t.string(),
  note: __t.string(),
});
export type PlanetParameter = __Infer<typeof PlanetParameter>;

export const Requirement = __t.object("Requirement", {
  id: __t.u64(),
  roundId: __t.u64(),
  kind: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  threshold: __t.string(),
  derivedFrom: __t.array(__t.string()),
  because: __t.string(),
  becauseField: __t.string(),
});
export type Requirement = __Infer<typeof Requirement>;

export const ResearchLog = __t.object("ResearchLog", {
  id: __t.u64(),
  roomId: __t.u64(),
  text: __t.string(),
  at: __t.timestamp(),
});
export type ResearchLog = __Infer<typeof ResearchLog>;

export const Result = __t.object("Result", {
  id: __t.u64(),
  roundId: __t.u64(),
  kind: __t.string(),
  pass: __t.bool(),
  reason: __t.string(),
  fact: __t.string(),
});
export type Result = __Infer<typeof Result>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  host: __t.identity(),
  get phase() {
    return Phase;
  },
  currentRoundId: __t.option(__t.u64()),
  nextRoundId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomCleanup = __t.object("RoomCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.u64(),
});
export type RoomCleanup = __Infer<typeof RoomCleanup>;

export const Round = __t.object("Round", {
  id: __t.u64(),
  roomId: __t.u64(),
  get status() {
    return RoundStatus;
  },
  planetName: __t.string(),
  twist: __t.string(),
  massBudget: __t.u32(),
  cheapestMass: __t.u32(),
  solarPerArray: __t.f64(),
  nightBand: __t.u8(),
  thermalLoad: __t.u8(),
  co2Atmosphere: __t.bool(),
  iceAvailable: __t.bool(),
  bermsRequired: __t.u8(),
  gravity: __t.f64(),
  headline: __t.string(),
  scaleText: __t.string(),
  funFacts: __t.array(__t.string()),
  briefingEndsAt: __t.option(__t.timestamp()),
  buildEndsAt: __t.option(__t.timestamp()),
  success: __t.option(__t.bool()),
});
export type Round = __Infer<typeof Round>;

// The tagged union or sum type for the algebraic type `RoundStatus`.
export const RoundStatus = __t.enum("RoundStatus", {
  Researching: __t.unit(),
  Ready: __t.unit(),
  Active: __t.unit(),
  Done: __t.unit(),
});
export type RoundStatus = __Infer<typeof RoundStatus>;

export const ServerConfig = __t.object("ServerConfig", {
  id: __t.u32(),
  owner: __t.identity(),
  server: __t.option(__t.identity()),
});
export type ServerConfig = __Infer<typeof ServerConfig>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Session = __Infer<typeof Session>;

export const Tile = __t.object("Tile", {
  id: __t.u64(),
  roundId: __t.u64(),
  index: __t.u8(),
  kind: __t.string(),
});
export type Tile = __Infer<typeof Tile>;

