// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ParamInput,
  BecauseInput,
} from "./types";

export default {
  roomId: __t.u64(),
  planetName: __t.string(),
  get params() {
    return __t.array(ParamInput);
  },
  twist: __t.string(),
  headline: __t.string(),
  scaleText: __t.string(),
  get because() {
    return __t.array(BecauseInput);
  },
  funFacts: __t.array(__t.string()),
};
