// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roundId: __t.u64().name("round_id"),
  field: __t.string(),
  num: __t.option(__t.f64()),
  flag: __t.option(__t.bool()),
  unit: __t.string(),
  status: __t.string(),
  sourceLabel: __t.string().name("source_label"),
  sourceUrl: __t.string().name("source_url"),
  note: __t.string(),
});
