// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roundId: __t.u64().name("round_id"),
  kind: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  threshold: __t.string(),
  derivedFrom: __t.array(__t.string()).name("derived_from"),
  because: __t.string(),
  becauseField: __t.string().name("because_field"),
});
