// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoundStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  get status() {
    return RoundStatus;
  },
  planetName: __t.string().name("planet_name"),
  massBudget: __t.u32().name("mass_budget"),
  buildEndsAt: __t.option(__t.timestamp()).name("build_ends_at"),
});
