// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ServerInfo = __t.object("ServerInfo", {
  id: __t.u32(),
  sharedVersion: __t.string(),
  moonNightBand: __t.u8(),
});
export type ServerInfo = __Infer<typeof ServerInfo>;

